import type { Metadata } from "next"
import localFont from "next/font/local"
import "./index.scss"
import Container from "@/components/Global/Container"
import Navbar from "@/components/Navbar/Navbar"

const spaceGrotesk = localFont({
  src: [
    {
      path: "./fonts/SpaceGrotesk-VariableFont_wght.woff",
    },
    {
      path: "./fonts/SpaceGrotesk-VariableFont_wght.ttf",
    },
  ],
  variable: "--font-spaceGrotesk",
})

export const metadata: Metadata = {
  title: "Positivus",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${spaceGrotesk.className} `}>
        <Container>
          <Navbar />
          {children}
        </Container>
      </body>
    </html>
  )
}
